### ISSUE TITLE
Inference across spatial areas

### ISSUE THREAD

**Issue by gabrieltseng** [WorldCereal/presto-worldcereal#5]
- [x] Define spatial areas which are prone to artefacts in the currently deployed system
- [x] Export tif files for those areas
- [ ] Run inference with the trained model against those areas

**Comment by kvantricht** [comment]
@gabrieltseng @rubencart I'd like to have your feedback on a sample file for this task. You can get it [here](https://artifactory.vgt.vito.be/auxdata-public/worldcereal/presto/testdata/belgium_good_2020-12-01_2021-11-30.nc)

Patch size is 101X101 10m pixels, this example is one over Belgium. Data is fairly compatible with the training data.
You'll find 12 timestamps in the files and 16 variables (+ `crs` so you can just visualize the patch). `lat/lon` can be derived from the coordinates, though they are in UTM at the moment. I think all required Presto inputs are there (no `DW` of course) and also the WorldCereal cropland classification is included.

Can you let me know what you'd like to see differently? At the moment I have 12 of these patches. Because they're small, the OpenEO extraction goes quite fast. I can add more patches, but also increase patch size. Just let me know what you think makes sense.

**Comment by rubencart** [comment]
I opened the file using `xarray` and it looks good to me :). Would the necessary conversion/preprocessing to Presto input be similar to what's currently in [`row_to_arrays`](https://github.com/WorldCereal/presto-worldcereal/blob/96b2954aa79435d7092762dad19b29b34e9e32f8/src/dataset.py#L51)? That would be convenient I guess.

**Comment by kvantricht** [comment]
> enEO extraction goes quite fast. I can add more patches, but also increase patch size. Just let me know what you think makes sense.

well ... `row_to_arrays` works on `Series` so I'm not sure how compatible you want it to be. I'm making sure the conversions that need to be done are the seem as on the training data. In the next version with `B8A` included I'll add lat/lon variables as well so we can easily load them for serving Presto.

**Comment by gabrieltseng** [comment]
re: `rows_to_arrays`, it ended up being easier to [write a new function](https://github.com/WorldCereal/presto-worldcereal/blob/839dabc1793acef918082fa018169ee55d767f88/src/dataset.py#L185).

**Comment by kvantricht** [comment]
@gabrieltseng seems explicitly adding lat/lon as variables [is now unnecessary](https://github.com/WorldCereal/presto-worldcereal/commit/839dabc1793acef918082fa018169ee55d767f88)?

**Comment by gabrieltseng** [comment]
> seems explicitly adding lat/lon as variables [is now unnecessary](https://github.com/WorldCereal/presto-worldcereal/commit/839dabc1793acef918082fa018169ee55d767f88)?

Yes 🙂 thanks @kvantricht
